In [4]:
def join_strings(a, b, sep):
  res = str(a) + sep + str(b)
  return res



In [5]:
join_strings('hey', 'you!')

TypeError: ignored

In [6]:
join_strings('hey', 123, ' ')

'hey 123'

In [9]:
join_strings(a='hey', sep=' ', b=123)

'hey 123'

In [10]:
join_strings('hey', sep=' ', b=123)

'hey 123'

In [13]:
join_strings('hey', ' ', b=123)

TypeError: ignored

In [14]:
join_strings('hey', b=' ', 123)

SyntaxError: ignored

In [34]:
def join_strings(a, b, sep=' ', repeat=1):
  res = ''
  for i in range(repeat):
    res += str(a) + sep + str(b)

  print(res)

  return res


def separate_strings(a, b):
  if b in a:
    split = a.find(b)
    res = (a[:split], a[split:])
    return res



In [35]:
separate_strings('A long sentence', 's')

('A long ', 'sentence')

In [27]:
join_strings('hey', 'you')

hey you


'hey you'

In [21]:
join_strings('hey', 'you', sep='|', repeat=2)

'hey|youhey|you'

In [22]:
join_strings('hey', 'you', repeat=2)

'hey youhey you'

In [23]:
join_strings('hello', 'blah', repeat=2)

'hello blahhello blah'

In [25]:
print(res)

NameError: ignored

# IDE (Integrated Development Environment)

- Visual Studio Code
- PyCharm
- Sublime Text
- Spyder

A docstring example:

In [37]:
def translate_word(word, dictionary, return_original=False, ignore_case=True):
    """Finds word in a dictionary and returns translation.

    This function takes a word in one language and a dictionary containing 
    translations as arguments. It looks for a word in the dictionary and, if found
    returns the translation. If the word is not in the dictionary, the function returns
    None or, the original word if return_original=True. The ignore_case argument specifies
    if the search should be case-sensitive or not.

    Parameters
    ----------
    word : str
        A word to look up in the dictionary.
    dictionary: dict
        A dictionary containing words (keys) and their translations (values).
    return_original: bool
        If true, the function returns the original word if no translation is found.
    ignore_case: bool
        If true, the words and translations are both converted to lowercase and than compared.

    Returns
    -------
    str, None
        A translated word, an original word or None.

    """
    

In [36]:
'A string'
"A string"
"""A string
Another string
and another string"""

'A string\nAnother string\nand another string'

In [ ]:
translate_word()

In [38]:
def add_numbers(a, b):
  if type(a) is int:
    return a + b
  else:
    return None

  

In [39]:
add_numbers(2, 3)

5

In [41]:
a = add_numbers('2', 3)
type(a)

NoneType

In [43]:
a is None

True

In [45]:
None

In [46]:
numpy

NameError: ignored

In [47]:
import numpy as np


In [50]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [51]:
a.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [52]:
a.reshape(2,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])