In [1]:
import numpy as np
import pandas as pd
import seaborn as sns


In [2]:
a = np.array([1, 3, 4, 5, 6, 10])
a

array([ 1,  3,  4,  5,  6, 10])

In [3]:
a.shape

(6,)

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.linspace(1, 10, 30)

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [6]:
rng = np.random.default_rng()

In [7]:
rng.integers(1, 10, 20)

array([4, 2, 1, 8, 2, 4, 3, 2, 7, 6, 2, 5, 7, 4, 8, 7, 6, 6, 1, 2])

In [9]:
numbers = rng.uniform(size=20)

In [10]:
numbers

array([0.03860078, 0.78446052, 0.3918291 , 0.76321461, 0.24191319,
       0.45905934, 0.75007153, 0.43077895, 0.87597041, 0.07009454,
       0.02392426, 0.62958902, 0.76224054, 0.96368116, 0.38440165,
       0.95382225, 0.15059427, 0.79474773, 0.25577111, 0.94580683])

In [11]:
numbers > .5

array([False,  True, False,  True, False, False,  True, False,  True,
       False, False,  True,  True,  True, False,  True, False,  True,
       False,  True])

In [12]:
numbers_list = [0.03860078, 0.78446052, 0.3918291 , 0.76321461, 0.24191319,
       0.45905934, 0.75007153, 0.43077895, 0.87597041, 0.07009454,
       0.02392426, 0.62958902, 0.76224054, 0.96368116, 0.38440165,
       0.95382225, 0.15059427, 0.79474773, 0.25577111, 0.94580683]

In [13]:
type(numbers_list)

list

In [14]:
numbers_list > .5

TypeError: '>' not supported between instances of 'list' and 'float'

In [15]:
numbers_bool = []
for n in numbers_list:
  if n > .5:
    numbers_bool.append(True)
  else:
    numbers_bool.append(False)

numbers_bool

[False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 True]

In [17]:
np_bool = numbers > .5
np_bool

array([False,  True, False,  True, False, False,  True, False,  True,
       False, False,  True,  True,  True, False,  True, False,  True,
       False,  True])

In [18]:
numbers

array([0.03860078, 0.78446052, 0.3918291 , 0.76321461, 0.24191319,
       0.45905934, 0.75007153, 0.43077895, 0.87597041, 0.07009454,
       0.02392426, 0.62958902, 0.76224054, 0.96368116, 0.38440165,
       0.95382225, 0.15059427, 0.79474773, 0.25577111, 0.94580683])

In [20]:
numbers[3:7]

array([0.76321461, 0.24191319, 0.45905934, 0.75007153])

In [21]:
numbers[np_bool]

array([0.78446052, 0.76321461, 0.75007153, 0.87597041, 0.62958902,
       0.76224054, 0.96368116, 0.95382225, 0.79474773, 0.94580683])

In [22]:
numbers[numbers > .5]

array([0.78446052, 0.76321461, 0.75007153, 0.87597041, 0.62958902,
       0.76224054, 0.96368116, 0.95382225, 0.79474773, 0.94580683])

In [23]:
numbers > .5

array([False,  True, False,  True, False, False,  True, False,  True,
       False, False,  True,  True,  True, False,  True, False,  True,
       False,  True])

In [24]:
numbers

array([0.03860078, 0.78446052, 0.3918291 , 0.76321461, 0.24191319,
       0.45905934, 0.75007153, 0.43077895, 0.87597041, 0.07009454,
       0.02392426, 0.62958902, 0.76224054, 0.96368116, 0.38440165,
       0.95382225, 0.15059427, 0.79474773, 0.25577111, 0.94580683])

Return a array containing only values smaller than .5 from `numbers`.

In [25]:
numbers[numbers < .5]

array([0.03860078, 0.3918291 , 0.24191319, 0.45905934, 0.43077895,
       0.07009454, 0.02392426, 0.38440165, 0.15059427, 0.25577111])

In [26]:
numbers[numbers > .5]

array([0.78446052, 0.76321461, 0.75007153, 0.87597041, 0.62958902,
       0.76224054, 0.96368116, 0.95382225, 0.79474773, 0.94580683])

In [27]:
np_bool = numbers > .5

In [28]:
np_bool

array([False,  True, False,  True, False, False,  True, False,  True,
       False, False,  True,  True,  True, False,  True, False,  True,
       False,  True])

In [29]:
~np_bool

array([ True, False,  True, False,  True,  True, False,  True, False,
        True,  True, False, False, False,  True, False,  True, False,
        True, False])

In [30]:
numbers[np_bool]

array([0.78446052, 0.76321461, 0.75007153, 0.87597041, 0.62958902,
       0.76224054, 0.96368116, 0.95382225, 0.79474773, 0.94580683])

In [31]:
numbers[~np_bool]

array([0.03860078, 0.3918291 , 0.24191319, 0.45905934, 0.43077895,
       0.07009454, 0.02392426, 0.38440165, 0.15059427, 0.25577111])

In [32]:
s1 = np.array([True, False, False, False])
s2 = np.array([False, True, False, False])
s3 = np.array([False, False, True, False])

s1

array([ True, False, False, False])

In [33]:
s2

array([False,  True, False, False])

In [34]:
s3

array([False, False,  True, False])

In [35]:
~s3

array([ True,  True, False,  True])

# Logical **and**

In [39]:
s1 & s2


array([False, False, False, False])

In [40]:
s2 & s3

array([False, False, False, False])

In [42]:
s3 & ~s1

array([False, False,  True, False])

In [44]:
~s1

array([False,  True,  True,  True])

## Logical **or**

In [37]:
s1 | s2

array([ True,  True, False, False])

In [41]:
s2 | s3

array([False,  True,  True, False])

In [43]:
s1 | ~s1

array([ True,  True,  True,  True])

In [ ]:
if a > 3 and a < 6:
  print('blabla')

In [48]:
numbers = rng.integers(0, 100, 30)
numbers

array([75, 43,  9,  3, 80, 91, 10, 82, 38, 71,  1, 88, 25, 75, 99, 88, 56,
       92, 73, 20, 78, 80, 68, 81, 95, 75, 73, 79, 33, 73])

From `numbers` select:

1. All numbers that are divisible by 2 (even) AND smaller than 50.
2. All numbers that are even OR larger than 90.
3. All numbers that are not divisible by 3 AND smaller than 20.

In [49]:
numbers[(numbers % 2 == 0) & (numbers < 50)]

array([10, 38, 20])

In [52]:
numbers[(numbers % 2 == 0) | (numbers > 90)]


array([80, 91, 10, 82, 38, 88, 99, 88, 56, 92, 20, 78, 80, 68, 95])

In [54]:
numbers[~(numbers % 3 == 0) & (numbers < 20)]

array([10,  1])

In [55]:
numbers

array([75, 43,  9,  3, 80, 91, 10, 82, 38, 71,  1, 88, 25, 75, 99, 88, 56,
       92, 73, 20, 78, 80, 68, 81, 95, 75, 73, 79, 33, 73])

In [57]:
np.where(numbers == 80)

(array([ 4, 21]),)

In [58]:
numbers == 80

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False])

In [59]:
numbers[4]

np.int64(80)

In [60]:
numbers[21]

np.int64(80)

In [61]:
a = rng.integers(1, 100, (10,10))

In [62]:
a

array([[75,  3, 55, 76, 53, 13, 83, 83, 80, 22],
       [77, 90, 62, 35, 74, 31, 90, 81, 30, 15],
       [29, 49, 24, 53, 60, 17, 85, 26, 32, 80],
       [40, 34, 30, 48, 67, 27, 83, 24, 31, 21],
       [68, 24, 91, 34, 74, 28, 45, 20, 31, 93],
       [85, 87, 10, 42, 44,  3, 23, 51, 35, 12],
       [18, 36, 23, 22, 48, 41, 72, 42,  6, 43],
       [59, 65, 59, 64, 53, 41, 44, 52, 91, 46],
       [27,  4, 28,  5, 63, 46, 44, 24,  5, 34],
       [74, 15, 17,  2, 47, 25, 89, 82, 92, 97]])

In [63]:
a[a % 2 == 0]

array([76, 80, 22, 90, 62, 74, 90, 30, 24, 60, 26, 32, 80, 40, 34, 30, 48,
       24, 68, 24, 34, 74, 28, 20, 10, 42, 44, 12, 18, 36, 22, 48, 72, 42,
        6, 64, 44, 52, 46,  4, 28, 46, 44, 24, 34, 74,  2, 82, 92])

In [65]:
(a % 2 == 0).shape

(10, 10)

In [66]:
a > 50

array([[ True, False,  True,  True,  True, False,  True,  True,  True,
        False],
       [ True,  True,  True, False,  True, False,  True,  True, False,
        False],
       [False, False, False,  True,  True, False,  True, False, False,
         True],
       [False, False, False, False,  True, False,  True, False, False,
        False],
       [ True, False,  True, False,  True, False, False, False, False,
         True],
       [ True,  True, False, False, False, False, False,  True, False,
        False],
       [False, False, False, False, False, False,  True, False, False,
        False],
       [ True,  True,  True,  True,  True, False, False,  True,  True,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [ True, False, False, False, False, False,  True,  True,  True,
         True]])

In [67]:
import pandas as pd

Pandas DataFrame

In [72]:
df_dict = {
    'person': [1, 2, 3, 4, 5],
    'weight': [80, 70, 120, 77, 46],
    'height': [183, 154.5, 163.4, 180., 171.1]
}
df_dict

{'person': [1, 2, 3, 4, 5],
 'weight': [80, 70, 120, 77, 46],
 'height': [183, 154.5, 163.4, 180.0, 171.1]}

In [74]:
df = pd.DataFrame(df_dict)

In [75]:
df

person  weight  height
0       1      80   183.0
1       2      70   154.5
2       3     120   163.4
3       4      77   180.0
4       5      46   171.1

In [71]:
type(df)

pandas.core.frame.DataFrame

In [76]:
df

person  weight  height
0       1      80   183.0
1       2      70   154.5
2       3     120   163.4
3       4      77   180.0
4       5      46   171.1

In [77]:
df.columns

Index(['person', 'weight', 'height'], dtype='object')

In [78]:
df['height']

0    183.0
1    154.5
2    163.4
3    180.0
4    171.1
Name: height, dtype: float64

In [79]:
type(df['height'])

pandas.core.series.Series

In [80]:
df.height

0    183.0
1    154.5
2    163.4
3    180.0
4    171.1
Name: height, dtype: float64

In [81]:
df.Height

AttributeError: 'DataFrame' object has no attribute 'Height'

In [82]:
df

person  weight  height
0       1      80   183.0
1       2      70   154.5
2       3     120   163.4
3       4      77   180.0
4       5      46   171.1

In [84]:
df[['height', 'person']]

height  person
0   183.0       1
1   154.5       2
2   163.4       3
3   180.0       4
4   171.1       5

In [87]:
columns = ['height', 'person']
df[columns]

height  person
0   183.0       1
1   154.5       2
2   163.4       3
3   180.0       4
4   171.1       5

In [88]:
df

person  weight  height
0       1      80   183.0
1       2      70   154.5
2       3     120   163.4
3       4      77   180.0
4       5      46   171.1

In [92]:
df['height']

0    183.0
1    154.5
2    163.4
3    180.0
4    171.1
Name: height, dtype: float64

In [93]:
df['height'][0]

np.float64(183.0)

In [94]:
df['height'][1]

np.float64(154.5)

In [95]:
df['height'][1:]

1    154.5
2    163.4
3    180.0
4    171.1
Name: height, dtype: float64

In [97]:
df

person  weight  height
0       1      80   183.0
1       2      70   154.5
2       3     120   163.4
3       4      77   180.0
4       5      46   171.1

In [98]:
df.loc[2, 'weight']

np.int64(120)

In [103]:
df.loc[2:3, ['height', 'person']]

height  person
2   163.4       3
3   180.0       4

person      3.0
weight    120.0
height    163.4
Name: 2, dtype: float64