In [1]:
2+2

4

In [3]:
import numpy as np

In [23]:
lol = [[1, 2, 3], [4, 5,6], [7, 8, 10]]

In [24]:
lol

[[1, 2, 3], [4, 5, 6], [7, 8, 10]]

In [25]:
len(lol)

3

In [26]:
lol[0]

[1, 2, 3]

In [27]:
lol[1]

[4, 5, 6]

In [28]:
lol[2][1]

8

In [29]:
mat = np.array(lol)

In [30]:
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [31]:
mat[2][1]

np.int64(8)

In [32]:
type(mat)

numpy.ndarray

In [33]:
type(mat[2][1])

numpy.int64

In [36]:
mat[2][1] / 2.4

np.float64(3.3333333333333335)

In [37]:
float(mat[2][1] / 2.4)

3.3333333333333335

In [38]:
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [39]:
mat[1, 2]

np.int64(6)

In [40]:
mat[1][2]

np.int64(6)

In [41]:
mat[0, 0:3]

array([1, 2, 3])

In [42]:
mat[1, 0:3]

array([4, 5, 6])

In [44]:
mat[1, 1:]

array([5, 6])

In [45]:
mat[:, 1]

array([2, 5, 8])

In [46]:
mat[:, 1:3]

array([[ 2,  3],
       [ 5,  6],
       [ 8, 10]])

In [47]:
mat.shape

(3, 3)

In [49]:
mat.ndim

2

In [50]:
mat + 3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 13]])

In [51]:
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [52]:
mat - 1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 9]])

In [54]:
mat[0, :] = mat[0, :] - 1
mat

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [55]:
a = 3
a = a - 1
a

2

In [56]:
mat * 2

array([[ 0,  2,  4],
       [ 8, 10, 12],
       [14, 16, 20]])

In [57]:
mat / 2

array([[0. , 0.5, 1. ],
       [2. , 2.5, 3. ],
       [3.5, 4. , 5. ]])

In [60]:
sr = mat ** (1/2)

In [62]:
sr

array([[0.        , 1.        , 1.41421356],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.16227766]])

In [63]:
mat + sr

array([[ 0.        ,  2.        ,  3.41421356],
       [ 6.        ,  7.23606798,  8.44948974],
       [ 9.64575131, 10.82842712, 13.16227766]])

In [64]:
mat * sr

array([[ 0.        ,  1.        ,  2.82842712],
       [ 8.        , 11.18033989, 14.69693846],
       [18.52025918, 22.627417  , 31.6227766 ]])

In [65]:
mat.shape

(3, 3)

In [66]:
sr.shape

(3, 3)

In [67]:
mat + sr[0, :]

array([[ 0.        ,  2.        ,  3.41421356],
       [ 4.        ,  6.        ,  7.41421356],
       [ 7.        ,  9.        , 11.41421356]])

In [68]:
mat

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [69]:
sr[0, :]

array([0.        , 1.        , 1.41421356])

In [70]:
mat + sr[0, :2]

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [71]:
sr[0, :2]

array([0., 1.])

In [72]:
mat

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [73]:
data = mat * sr

In [74]:
data

array([[ 0.        ,  1.        ,  2.82842712],
       [ 8.        , 11.18033989, 14.69693846],
       [18.52025918, 22.627417  , 31.6227766 ]])

In [75]:
np.mean(data)

np.float64(12.275128694005518)

In [76]:
np.mean(data[:, 0])

np.float64(8.840086392484045)

In [77]:
np.std(data[:, 0])

np.float64(7.584163713955884)

In [81]:
np.round(np.mean(data, axis=1), 2)

array([ 1.28, 11.29, 24.26])

In [82]:
rng = np.random.default_rng()

In [89]:
ri = rng.integers(0, 10, (100, 100))

In [90]:
ri.shape

(100, 100)

In [91]:
np.save('ri.npy', ri)

In [92]:
mat

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [93]:
mat.T

array([[ 0,  4,  7],
       [ 1,  5,  8],
       [ 2,  6, 10]])

In [95]:
np.concat([mat, mat.T], axis=1)

array([[ 0,  1,  2,  0,  4,  7],
       [ 4,  5,  6,  1,  5,  8],
       [ 7,  8, 10,  2,  6, 10]])

In [96]:
mat2 = np.concat([mat, mat.T], axis=1)

In [97]:
mat2

array([[ 0,  1,  2,  0,  4,  7],
       [ 4,  5,  6,  1,  5,  8],
       [ 7,  8, 10,  2,  6, 10]])

In [99]:
mat2.shape

(3, 6)

In [100]:
np.reshape(mat2, 18)

array([ 0,  1,  2,  0,  4,  7,  4,  5,  6,  1,  5,  8,  7,  8, 10,  2,  6,
       10])

In [101]:
np.reshape(mat2, (9,2))

array([[ 0,  1],
       [ 2,  0],
       [ 4,  7],
       [ 4,  5],
       [ 6,  1],
       [ 5,  8],
       [ 7,  8],
       [10,  2],
       [ 6, 10]])

In [102]:
np.reshape(mat2, (8,2))

ValueError: cannot reshape array of size 18 into shape (8,2)

In [106]:
np.zeros((3,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [107]:
np.ones((3,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [109]:
[i for i in range(3,12)]

[3, 4, 5, 6, 7, 8, 9, 10, 11]

In [113]:
np.arange(100).reshape((10, 10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [116]:
np.linspace(0, 1, 100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747